version: "3.9"

services:
  admin-svc:
    image: ghcr.io/tuannp1996/admin-svc:latest
    container_name: admin-svc
    restart: unless-stopped
    volumes:
      # Mount Docker socket to inspect other containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount config (so you can edit without rebuilding)
      - ./config.yaml:/app/config.yaml:ro
      # Mount .env so the app can load secrets at startup
      - ./.env:/app/.env:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: host   # Allows checking localhost services; change if not needed
